-- Final PostgreSQL schema for Telegram Cloud Drive.
-- Apply once against the Postgres database (the `postgres` compose service runs this
-- automatically on first init — it is mounted into /docker-entrypoint-initdb.d).
--
-- Migration note: this project moved from Turso (libSQL/SQLite) to self-hosted
-- PostgreSQL. SQLite-isms were translated as follows:
--   datetime('now')            -> now_text()        (UTC text, identical format)
--   INTEGER PRIMARY KEY AUTO…  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   byte sizes / msg ids       -> BIGINT            (can exceed 2^31)
--   INSERT OR IGNORE/REPLACE   -> ON CONFLICT … DO NOTHING / DO UPDATE
--   name = ? COLLATE NOCASE    -> lower(name) = lower(?)

-- Timestamps are kept as TEXT in the exact SQLite format ('YYYY-MM-DD HH:MM:SS', UTC)
-- so the web (sqliteToMs) and bot date parsing keep working unchanged after the migration.
CREATE OR REPLACE FUNCTION now_text() RETURNS text
    LANGUAGE sql VOLATILE AS
$$ SELECT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS') $$;

CREATE TABLE IF NOT EXISTS folders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    parent_id  BIGINT REFERENCES folders(id) ON DELETE CASCADE,
    is_private INTEGER NOT NULL DEFAULT 0,        -- 1 = hidden in the PIN-gated Private space
    created_at TEXT NOT NULL DEFAULT now_text(),
    updated_at TEXT NOT NULL DEFAULT now_text(),
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         TEXT UNIQUE NOT NULL,
    title        TEXT NOT NULL,
    kind         TEXT NOT NULL CHECK (kind IN ('archive','media')),
    total_parts  INTEGER NOT NULL DEFAULT 0,
    total_size   BIGINT NOT NULL DEFAULT 0,
    is_favorite  INTEGER NOT NULL DEFAULT 0,
    is_private   INTEGER NOT NULL DEFAULT 0,      -- 1 = hidden in the PIN-gated Private space
    date_added   TEXT NOT NULL DEFAULT now_text(),
    updated_at   TEXT NOT NULL DEFAULT now_text(),
    deleted_at   TEXT,                            -- NULL = active; set = in trash
    folder_id    BIGINT REFERENCES folders(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS parts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id        BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    part_number    INTEGER NOT NULL,
    channel_msg_id BIGINT UNIQUE NOT NULL,
    file_name      TEXT,
    file_size      BIGINT NOT NULL DEFAULT 0,
    file_id        TEXT,
    uploaded_at    TEXT,
    UNIQUE(item_id, part_number)
);

CREATE TABLE IF NOT EXISTS tags (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT UNIQUE NOT NULL,
    color TEXT NOT NULL DEFAULT ''   -- palette key (sage, ochre, …) or '' = derive from name
);

CREATE TABLE IF NOT EXISTS item_tags (
    item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, tag_id)
);

-- Thumbnail per-PART: an album (media group) = 1 multi-part item; every photo/video
-- has its own thumbnail. Item cover = thumbnail of the part with the smallest channel_msg_id.
CREATE TABLE IF NOT EXISTS thumbnails (
    part_id BIGINT PRIMARY KEY REFERENCES parts(id) ON DELETE CASCADE,
    mime    TEXT NOT NULL DEFAULT 'image/jpeg',
    data    TEXT NOT NULL                          -- base64
);

CREATE TABLE IF NOT EXISTS jobs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       TEXT NOT NULL CHECK (type IN ('delete','reindex')),
    item_id    BIGINT REFERENCES items(id) ON DELETE CASCADE,
    status     TEXT NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','running','done','error')),
    payload    TEXT,
    created_at TEXT NOT NULL DEFAULT now_text(),
    updated_at TEXT NOT NULL DEFAULT now_text()
);

-- Upload queue from web → executed by watcher.py. Two origins:
--   'local'  : file on the watcher machine, source_path = local path. Source NOT deleted.
--   'upload' : file uploaded via the browser (resumable) into a staging dir shared by
--              web & watcher. source_path = staged file. cleanup_source=1 → watcher deletes it.
CREATE TABLE IF NOT EXISTS upload_jobs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           TEXT NOT NULL CHECK (kind IN ('archive','media')),
    title          TEXT NOT NULL,
    tags           TEXT NOT NULL DEFAULT '',
    source_path    TEXT NOT NULL,                  -- local path (local) / staged file (upload)
    part_size      INTEGER NOT NULL DEFAULT 1500,  -- MB (archive only)
    origin         TEXT NOT NULL DEFAULT 'local'   -- 'local' | 'upload'
                     CHECK (origin IN ('local','upload')),
    cleanup_source INTEGER NOT NULL DEFAULT 0,     -- 1 = delete source_path after success
    parts_done     INTEGER NOT NULL DEFAULT 0,     -- checkpoint: parts already uploaded (for resume)
    total_bytes    BIGINT NOT NULL DEFAULT 0,      -- file size (display)
    status         TEXT NOT NULL DEFAULT 'queued'
                     CHECK (status IN ('queued','pending','running','done','error','canceled')),
    progress       INTEGER NOT NULL DEFAULT 0,     -- 0..100
    message        TEXT,                           -- detail/error
    created_at     TEXT NOT NULL DEFAULT now_text(),
    updated_at     TEXT NOT NULL DEFAULT now_text()
);

-- Generated subtitle tracks per part (original + translations). One row per language.
-- The VTT files live on the streamer's persistent /subtitles volume; this table just
-- tells the web player which languages are available.
CREATE TABLE IF NOT EXISTS subtitles (
    part_id    BIGINT NOT NULL,
    lang       TEXT NOT NULL,                  -- ISO-639-1 (en, id, …) or 'orig'
    created_at TEXT NOT NULL DEFAULT now_text(),
    PRIMARY KEY (part_id, lang)
);

-- Owner-managed key/value bot settings (e.g. web_url) — created at runtime by bot.py too.
CREATE TABLE IF NOT EXISTS bot_settings (
    key   TEXT PRIMARY KEY,
    value TEXT
);

-- Telegram users allowed to use the bot (besides OWNER_USER_ID).
CREATE TABLE IF NOT EXISTS authorized_users (
    user_id    BIGINT PRIMARY KEY,
    username   TEXT,
    first_name TEXT,
    added_at   TEXT NOT NULL DEFAULT now_text()
);

-- Web/mobile JWT auth (register/login/me) — consumed by the .NET API (Sarastya-project-api).
-- The drive is single-tenant: this table is auth-only (no user_id on folders/items); JWT just
-- gates access. EF entities in the API map to this table and run NO prod migrations. Conventions
-- match the rest of the schema: BIGINT IDENTITY ids, TEXT 'YYYY-MM-DD HH:MM:SS' UTC timestamps,
-- case-insensitive unique email via lower(). Mirrors Sarastya-project-api/db/users.sql.
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at    TEXT NOT NULL DEFAULT now_text()
);

-- Case-insensitive unique email (matches the API's lower(email) lookup on login).
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (lower(email));

CREATE INDEX IF NOT EXISTS idx_upload_jobs_status ON upload_jobs(status);
CREATE INDEX IF NOT EXISTS idx_parts_item      ON parts(item_id);
CREATE INDEX IF NOT EXISTS idx_thumbnails_part ON thumbnails(part_id);
CREATE INDEX IF NOT EXISTS idx_items_kind      ON items(kind);
CREATE INDEX IF NOT EXISTS idx_items_deleted   ON items(deleted_at);
CREATE INDEX IF NOT EXISTS idx_items_favorite  ON items(is_favorite) WHERE is_favorite = 1;
CREATE INDEX IF NOT EXISTS idx_items_private   ON items(is_private);
CREATE INDEX IF NOT EXISTS idx_folders_private ON folders(is_private);
CREATE INDEX IF NOT EXISTS idx_subtitles_part  ON subtitles(part_id);

-- ---------------------------------------------------------------------------
-- Realtime change notification (web SSE) ----------------------------------
-- Any change to the drive's visible data emits a NOTIFY on the 'drive_changed'
-- channel. The web endpoint /api/events holds ONE shared LISTEN connection and
-- pushes a tiny signal to every connected browser, which then refreshes — so
-- files indexed by the bot/watcher (or edits from another session) appear live,
-- without polling. Statement-level so a bulk write (e.g. indexing many parts,
-- which UPDATEs items) fires once per statement, not once per row. Triggers cover
-- the tables the drive view enumerates; parts/thumbnails are intentionally omitted
-- (adding parts UPDATEs items.total_* → already fires; covers load lazily anyway).
CREATE OR REPLACE FUNCTION notify_drive_change() RETURNS trigger
    LANGUAGE plpgsql AS
$$ BEGIN
    PERFORM pg_notify('drive_changed', TG_TABLE_NAME);
    RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS trg_notify_items ON items;
CREATE TRIGGER trg_notify_items AFTER INSERT OR UPDATE OR DELETE ON items
    FOR EACH STATEMENT EXECUTE FUNCTION notify_drive_change();

DROP TRIGGER IF EXISTS trg_notify_folders ON folders;
CREATE TRIGGER trg_notify_folders AFTER INSERT OR UPDATE OR DELETE ON folders
    FOR EACH STATEMENT EXECUTE FUNCTION notify_drive_change();

DROP TRIGGER IF EXISTS trg_notify_item_tags ON item_tags;
CREATE TRIGGER trg_notify_item_tags AFTER INSERT OR UPDATE OR DELETE ON item_tags
    FOR EACH STATEMENT EXECUTE FUNCTION notify_drive_change();

DROP TRIGGER IF EXISTS trg_notify_tags ON tags;
CREATE TRIGGER trg_notify_tags AFTER INSERT OR UPDATE OR DELETE ON tags
    FOR EACH STATEMENT EXECUTE FUNCTION notify_drive_change();

-- Upload-queue progress notification: a separate 'upload_changed' channel so the /upload page
-- can refresh live on job progress/status changes WITHOUT also waking the main drive grid (which
-- only LISTENs for the data it shows). Statement-level — one signal per UPDATE, not per row.
CREATE OR REPLACE FUNCTION notify_upload_change() RETURNS trigger
    LANGUAGE plpgsql AS
$$ BEGIN
    PERFORM pg_notify('upload_changed', TG_TABLE_NAME);
    RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS trg_notify_upload_jobs ON upload_jobs;
CREATE TRIGGER trg_notify_upload_jobs AFTER INSERT OR UPDATE OR DELETE ON upload_jobs
    FOR EACH STATEMENT EXECUTE FUNCTION notify_upload_change();
